fortraveler/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'post'

urlpatterns = [
    path('', views.show_main_page, name='main'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('upload/', views.upload, name='upload'),
    path('post/', views.search_result, name='search_result'),
    path('post/<int:pk>/', views.show_post_detail, name='post_detail'),
    path('profile/<int:pk>/', views.show_post_detail, name='profile_detail'),
    path('profile/', views.profile_page, name='profile'),
    path('post/<int:pk>/<int:comment_pk>/delete',views.comment_delete,name='comment_delete'),
    path('post/<int:pk>/delete', views.post_delete, name='post_delete'),
    path('post/<int:pk>/update', views.post_update, name='update'),
]

post/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User


class Category1(models.Model):
    category = models.CharField(max_length=20)
    class Meta:
        managed = False
        db_table = 'category1'
        verbose_name_plural = 'Categories1'
        
    def __str__(self): 
        return self.category
    
class Category2(models.Model):
    category = models.CharField(max_length=20)
    class Meta:
        managed = False
        db_table = 'category2'
        verbose_name_plural = 'Categories2'
        
    def __str__(self): 
        return self.category

    
class Post(models.Model):
    pn = models.AutoField(db_column='PN', primary_key=True)  # Field name made lowercase.
    title = models.CharField(max_length=50, blank=True, null=True)
    created_at = models.DateField(blank=True, null=True, auto_now_add = True)
    content = models.TextField(max_length=1000, blank=True, null=True)
    head_image = models.ImageField(upload_to="post/images/%Y/%m/%d",blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, max_length=20, db_column='author')
    category1 = models.ForeignKey(Category1, on_delete=models.CASCADE, null=True, db_column='category1')
    category2 = models.ForeignKey(Category2, on_delete=models.CASCADE, null=True, db_column='category2')
    # sub_category = models.CharField(max_length=20, blank=True, null=True)  보류

    class Meta:
        managed = False
        db_table = 'post'
        
    def __str__ (self):
        return self.title
    
    def get_absolute_url(self):
        return f'{self.pk}/'

    def get_image_url(self):
        return self.head_image[:].decode()


class Photo(models.Model):
    postnum = models.ForeignKey('Post', models.CASCADE, db_column='postnum', blank=True)
    image = models.ImageField(upload_to="post/images/%Y/%m/%d")

    class Meta:
        managed = False
        db_table = 'photo'
        
class Comment(models.Model):
    postnum = models.ForeignKey(Post, models.CASCADE, db_column='postnum')
    author = models.ForeignKey(User, models.CASCADE, db_column='author')
    content = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'comment'
    
        

post/views.py
import json
from unicodedata import category
from django.http import JsonResponse
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib import auth
from numpy import product
from .models import *
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.contrib.auth.hashers import check_password, make_password
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator

# Create your views here.

def show_main_page(request):
    return render(
        request,
        'post/index.html'
    )

def profile_page(request):
    User = get_user_model()
    
    if request.user.is_authenticated:
        mypost=Post.objects.filter(author=request.user)
    else:
        return render(request, 'post/login.html')
    post_count = len(mypost)
    
    return render(
        request,
        'post/profile.html',
        {
            'post_count' : post_count,
            'mypost':mypost,
        }
    )



def search_result(request):
    posts, query = None, None
    # 장고 검색 기능
    if 'q' in request.GET:  
        query = request.GET.get('q')
        # posts = Post.objects.all().filter(Q(title__icontains=query))
        category1 = Category1.objects.filter(category=query)
        category2 = Category2.objects.filter(category=query)
        
        if not category1.exists(): category_num1 = 0
        else: category_num1 = category1.values_list()[0][0]
        
        if not category2.exists(): category_num2 = 0
        else: category_num2 = category2.values_list()[0][0]
        
        posts = Post.objects.all().filter(Q(title__icontains=query) | Q(category1=category_num1) | Q(category2=category_num2))
        
    return render(request,
                'post/post_list.html',
                {'query' : query,
                'posts': posts})

def show_post_detail(request, pk):
    post = Post.objects.get(pk=pk)              # 해당 포스트만 가져옴
    photo = Photo.objects.filter(postnum_id=pk) # 해당 포스트의 사진만 가져옴
    comment=Comment()
    # print(pk)
    if request.method=='POST':
        if request.user.is_authenticated:
            content=request.POST['content']
            comment.content=content
            comment.postnum=post
            comment.author=request.user
            comment.save()
        else:
            return render(request, 'post/login.html')
    
    # page
    page=request.GET.get('page')
    comment=Comment.objects.filter(postnum_id=pk).order_by('-id')  #해당 포스트의 댓글만 가져옴
    paginator=Paginator(comment,10)
    repost=paginator.get_page(page)


    return render(
        request,
        'post/post_detail.html',
        {
            'post':post,
            'photo':photo,
            'comment':comment,
            'repost':repost,
        }
    )

@csrf_exempt
def comment_delete(request,pk,comment_pk):
    post = Post.objects.get(pk=pk)              # 해당 포스트만 가져옴
    photo = Photo.objects.filter(postnum_id=pk) # 해당 포스트의 사진만 가져옴
    # comment=Comment.objects.filter(postnum_id=pk).order_by('-id')
    # page
    page=request.GET.get('page')
    comment=Comment.objects.filter(postnum_id=pk).order_by('-id')  #해당 포스트의 댓글만 가져옴
    paginator=Paginator(comment,10)
    repost=paginator.get_page(page)
    if request.method=='POST':
        # comment.id가 삭제되어야함
        del_comment=Comment.objects.get(pk=comment_pk)
        del_comment.delete()
    return render(
        request,
        'post/post_detail.html',
        {
            'post':post,
            'photo':photo,
            'comment':comment,
            'repost':repost,
        }
    )
    # return redirect('/post/'+int(post.pk))
@csrf_exempt
def post_delete(request,pk):
    post = Post.objects.get(pk=pk)              # 해당 포스트만 가져옴
    # photo = Photo.objects.filter(postnum_id=pk) # 해당 포스트의 사진만 가져옴
    if request.method=='POST':
        if request.user.is_authenticated:
            # print(post.pk)
            post.delete()
        else:
            return render(request, 'post/login.html')
    return redirect("/post")

@csrf_exempt
def post_update(request,pk):
    # 포스트의 pk를 불러오고 pk빼고 나머지를 저장
    post=Post.objects.get(pk=pk)
    if request.method=='POST':
        post.title=request.POST['title']
        post.content=request.POST['content']
        post.category1_id=request.POST['city']
        post.category2_id=request.POST['category']
        # print(request.POST['title'])
        post.save()
        for idx, img in enumerate(request.FILES.getlist('files')):
            if idx == 0: 
                post.head_image=img
                post.save()
                photo=Photo.objects.filter(postnum_id=pk)
                photo.delete()
            else:
                photo=Photo()
                photo.postnum=post
                photo.image=img
                photo.save()
        return redirect('/')
    else:
        return render(request,'post/update.html',{'post':post})
    
    ...
@csrf_exempt
def upload(request):
    if request.method =='POST':
        title, content = request.POST.get('title',), request.POST.get('content', )
        main_category = request.POST.get('city')
        sub_category=request.POST.get('category')
    

        category_num1 = main_category
        category_num2 = sub_category
        
        post=Post()
        post.title = title
        post.content = content
        post.category1_id = category_num1
        post.category2_id = category_num2
        post.author = request.user
        
        for idx, img in enumerate(request.FILES.getlist('files')):
            if idx == 0: 
                post.head_image=img
                post.save()
            else:
                photo=Photo()
                photo.postnum=post
                photo.image=img
                photo.save()
            
        return redirect('/')
    
    else:
        return render(request, 'post/upload.html')


# Create your views here.
def register(request):   
    if request.method == 'POST':
        id = request.POST['id']
        password = request.POST['password']
        nickname = request.POST['nickname']
        
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(
                username=id, password=password
            )
            auth.login(request, user)
            return redirect('/')
        else:
            return render(request, 'post/register.html')
    return render(request, 'post/register.html')
        
        

def login(request):    
    # login으로 POST 요청이 들어왔을 때, 로그인 절차를 밟는다.
    if request.method == "POST":
        # login.html에서 넘어온 username과 password를 각 변수에 저장한다.
        id = request.POST['id']
        password = request.POST['password']
        user = auth.authenticate(request, username=id, password=password)
        
        if user is not None: 
            auth.login(request, user)
            return redirect('/')
        else:
            return render(request, 'post/login.html', {'error':'not user'})
    else:
        return render(request, 'post/login.html')

# 로그 아웃
def logout(request):
    auth.logout(request)
    return redirect('/')


''' mysql version
@csrf_exempt   
def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, user_name=username, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'main')
        else:
            return redirect('/'), {'error': 'username or password is incorrect'}
    else:
        return render(request, 'post/login.html')

@csrf_exempt
def register(request):
    print(request.method)
    if request == "POST":
        id = request.POST['user_name']
        passwd = request.POST['user_password']
        nickname = request.POST['user_nickname']
        
        if User.objects.filter(id=id).exists():
            return render(request, 'post/index.html')
        else:
            user = User.objects.create(id=id, passwd=make_password(passwd), nickname=nickname)
            user.save()
            return redirect('main')
    else: return render(request, 'post/register.html')

@csrf_exempt
def loginCheck(request):
    template_name = 'login.html'
    request.session['loginOk'] = False
    inputId == ''
    inputPassword == ''
    
    try:
        data = request.POST
        inputId = data['username']
        inputPassword = data['password']

    except (KeyError):
        context = {
            "uid": "empty",
            "upass": "empty",
        }
        return render(request, template_name, context)
    else:
        if User.objects.filter(username=inputId).exists():
            getUser = User.objects.get(username=inputId)
            if getUser.password == inputPassword:
                request.session['loginOk'] = True
                context = {
                    "result": "로그인 성공"
                }
            else:
                request.session['loginOk'] = False
                context = {
                    "result": "비밀번호가 틀렸습니다"
                }
        else:
            request.session['loginOk'] = False
            context = {
                "result": "존재하지 않는 id입니다"
            }
        return HttpResponse(json.dumps(context), content_type="application/json")
'''

post/templates/post/login.html
<!doctype html>

{% load static %}

<html lang="kr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'post/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/login.css' %}">

    <!-- Jquery -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!--sweetalert-->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <style>    
    </style>
</head>

<body>
    <div style="display: flex; flex-direction: column; align-items: center; width: 100%;">
        <div style="background-color: white; text-align: center; border-radius: 30px; border: solid 2px white; width: 600px; height: 750px; margin-top: 100px; background-color: white;">
            <div>
                <img style="margin-top: 20px;" text-align = center; src="https://fontmeme.com/permalink/220915/c6ef805ef970debb1312e27648f01afc.png"></img>
            </div>
            
            <form action="{% url 'post:login' %}" method="POST" >
                {% csrf_token %}
                <div style="padding-left: 100px;">
                    <div style="margin-top: 50px; width: 80%;" class="form-floating mb-3">
                        <input name ="id" type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                        <label for="floatingInput">아이디</label>
                    </div>
                    <div style="margin-top: 50px; width: 80%;" class="form-floating mb-3">
                        <input name ="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">비밀번호</label>
                    </div>
                </div>

                <div style="padding-left: 100px;">
                    <div style="margin-top: 30px; width: 80%;" class="form-floating">
                        <div style="padding-top: 30px;">
                            <input button type ="submit" id="login_btn" style="width: 70%; height: 40px;" value ="로그인" class="btn btn-info">
                        </div>
                        <div style="display: flex; flex-direction: row; justify-content: space-between; padding-top: 20px;">
                            <div type="button" style="text-decoration-line: none;">
                                <a href="register" style="text-decoration-line: none; color: black;">회원가입</a>
                            </div>
                            <div type="button" style="text-decoration-line: none";>
                                <body class="moving" style="width: 100vm; height: 100vh;">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {% comment %} <script>
        $('#login_btn').click(function () {

            let id = $('#input_id').val();
            let password = $('#input_password').val();
        
        
            $.ajax({
                url: "",
                data: {
                    id: id,
                    password: password
                },
                method: "POST",
        
        
                success: function (data) {
                    console.log("성공");
                    swal("로그인 성공!", "", "success");
                    location.replace('')
                },
                error: function (request, status, error) {
                    swal("아이디와 비밀번호를 확인하세요", "", "warning");
                    console.log("에러");
                },
                complete: function () {
                    console.log("보내기");
        
                }
            });
        });
    </script> {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous">
    </script>
</body>

</html>

post/templates/post/post_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>검색 상세 페이지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'post/css/detail.css' %}">
    <script scr = "js/jquery-3.6.1.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a href="{% url 'post:main' %}"><img class="forTraveler" src="{% static 'post/images/title/skyblue.png'%}"></img></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url 'post:profile' %}"><button type="button" class="btn btn-success">나의 정보</button></a>
                    <a class="nav-link active" href="{% url 'post:logout' %}"><button type="button" class="btn btn-outline-success">로그아웃</button></a>
                    {% else %}
                        <a class="nav-link active" aria-current="page" href="{% url 'post:login' %}"><button type="button" class="btn btn-success">로그인</button></a>
                        <a class="nav-link active" href="{% url 'post:register' %}"><button type="button" class="btn btn-outline-success">회원가입</button></a>
                        <!-- <a class="nav-link" href="#">Pricing</a> -->
                    {% endif %}
                </div>
            </div>
        </div>
    </nav><hr class="m-0">

    <div class="detail_page_main" style="margin-top: 30px;">
        <div class="container">
            <div class="detail_page_area">
                <div class="detail_page_row">
                    <div class="detail_page_nickname">
                        <h5 class="post_author">{{post.author}}</h5>
                    </div>
                    <div class="detail_page_title">
                        <h1>{{post.title}}</h1>
                    </div>
                    {% if post.author.id == user.pk %}
                    <div>
                        <form method="post" action="{% url 'post:post_delete' post.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">글 삭제하기</button>
                            
                        </form>
                        <button type="submit" class="btn btn-warning"><a style="text-decoration: none; color: white;"   href="{% url 'post:update' post.pk %}">글 수정하기</a></button>
                        
                    </div>                    
                    {% endif %}
                                        
                    <div class="detail_page_info">
                        <h6>{{post.created_at}} 조회수 따봉수</h6>
                    </div>
                </div>
                <hr>
                <div>
                    <div class="container">
                        <div class="row">
                            {% for p in photo %}
                            <img src="{{p.image.url}}" class="detail_image"></img>
                            {% endfor %}
                        </div>
    
                    </div>
                </div><hr>

                <div class="detail_page_content">
                    {{post.content}}
                </div>
            </div>
            {% if comment %}
            <div class="detail_page_comment">
                <div class="detail_page_comment_1">
                    <hr> 댓글
                    <span class = "detail_page_comment_count"> {{comment|length}}</span>
                </div>
            </div>
            {% endif %}
            
            <br>
            <!-- form date -->
            <form method="POST" action="{% url 'post:post_detail' post.pk %}">
                <div class="input-group mb-3">
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                    <input name="content" type="text" class="form-control" placeholder="댓글입력.." aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <button type="submit" class="input-group-text" id="basic-addon2">게시</button>
                    {% else %}
                    {% endif %}
                    
                    </div>
            </form>
            
            
            <br>
            {% for comment in repost %}
            <div class="detail_page_comment_info">
                <span class = "detail_page_comment_profileicon">
                    <img src="https://images-ext-1.discordapp.net/external/rWS9kuA0xfcxNXpHz83URFpeXXuu15ufeW8OGq1IFHw/https/fontmeme.com/permalink/220915/c6ef805ef970debb1312e27648f01afc.png" alt ="ForTravler" width="60" height="13">
                </span>
                <span class = "detail_page_comment_nickname">
                    {{comment.author.username}} {{comment.created_at}}
                    {% if comment.author.id == user.pk %}
                    <form method="post" action="{% url 'post:comment_delete' post.pk comment.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">삭제</button>
                    </form>
                    {% endif %}
                </span>
                <div class="detail_page_comment_content">
                    {{comment.content}} 
                    <hr>
                </div>
                {% empty %}
                댓글을 작성해보세요!
            </div>
            {% endfor %}

            <!-- {% for com in repost %}
            <h2>{{com.content}}</h2>
            {% endfor %} -->

            <!--page-->
            <div class="container">
                <nav aria-label="nav_page">
                    <ul class="pagination">
                            <li class="page-item">
                            {% if repost.has_previous %}
                            <a class="page-link" href="?page={{posts.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                            </a>
                            {% endif %}
                            </li>

                            {% for p in repost.paginator.page_range %}
                            <li class="page-item"><a class="page-link" href="?page={{p}}">{{p}}</a></li>
                            {% endfor %}
                            
                            {% if repost.has_next %}
                            <a class="page-link" href="?page={{repost.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                            {% endif %}


                        <!-- <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li> -->
                        <li class="page-item">
                        
                        </li>
                    </ul>
                </nav>
            </div>
        </div>   
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>    
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    
</body>
</html>

post/templates/post/profile.html
<!doctype html>
<html lang="ko-kr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Jquery -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <!-- material Icon-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>fortralver</title>
</head>

<body>
    

    <div
        style="display: flex; flex-direction: row; text-align: center; justify-content: center; padding-top: 60px; padding-right: 60px;">
        <div style="padding: 20px 60px;">
            <div style="display: flex;flex-direction: row;">
                <div style="width: 130px;
                    height: 130px; 
                    border-radius: 70%;
                    overflow: hidden;">
                    <img src="https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927" style="width: 100%;
                height: 100%;
                object-fit: cover;">
                </div>
            </div>
        </div>
        <div style="margin-top: 30px; text-align: left;">
            <div style="display: flex; flex-direction: row; margin-bottom: 20px; ">
                <div style="font-size: 26px; margin-right: 40px;">
                    {{user.username}}
                </div>
                <a href="setting.html">
                    <span style="color: black;" class="material-symbols-outlined" type="button">
                        settings
                    </span>
                </a>

            </div>

            <div style="margin-bottom: 10px;">
                내 게시물 {{post_count}}
            </div>
            <div>
                <b>name</b>
            </div>

        </div>
    </div>
    <div style="border-top: solid 2px; color: darkgrey;">
    </div>
    <div style="display: flex; flex-direction: row; justify-content: center; padding-top: 20px;">

        <div type="button" style="margin: 0 30px;">
            <span class="material-icons">
                apps
            </span>내 게시물
        </div>

        <div type="button" style="margin: 0 30px;"><span class="material-icons">
                bookmark_border
            </span>북마크</div>
    </div>

    

    <div style="width: 100%; min-width: 100%; display: flex; align-items: center; justify-content: center; margin-top: 30px;">
        <div class="container">
            <div class="row">
                {% for mypost in mypost %}
                <div class="col-4" style="margin-bottom:30px">
                    <a href="{% url 'post:profile_detail' mypost.pk %}">    
                        <span>
                            <img src="{{mypost.head_image.url}}" style="width: 100px; height: 100px; border-radius: 20px;">
                            <b>{{mypost.title}}</b>
                        </span>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>



        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>